Repository GoogleCloudPlatform/cloud-debug-proxy-common, pull requests merged in 2018-08, with the labels that each got.

#7 fix: do not throw for responses with empty lists
  src/wrapper.ts
  test/mocha.opts
  test/test-wrapper.ts
Labels: bug

#10 chore: ignore package-lock.json
  .gitignore
  package-lock.json
Labels: enhancement

#13 chore: use p-limit to rate-limit Promise.all
  package.json
  src/index.ts
Labels: enhancement

#18 feat: implement getBreakpointList
  src/index.ts
Labels: enhancement

#23 Allow for more customized authentication
  src/index.ts
  src/wrapper.ts
  test/fixtures/application_default_credentials_no_project.json
  test/test-wrapper.ts
Labels: cla: yes
